// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: messages.proto

package eventsbridge

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event represents a single event from the bob node
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogId         uint64                 `protobuf:"varint,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	Tick          uint32                 `protobuf:"varint,2,opt,name=tick,proto3" json:"tick,omitempty"`
	Epoch         uint32                 `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	EventType     uint32                 `protobuf:"varint,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	TxHash        string                 `protobuf:"bytes,5,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Body          *structpb.Struct       `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	IndexInTick   uint32                 `protobuf:"varint,8,opt,name=index_in_tick,json=indexInTick,proto3" json:"index_in_tick,omitempty"`
	LogDigest     string                 `protobuf:"bytes,9,opt,name=log_digest,json=logDigest,proto3" json:"log_digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetLogId() uint64 {
	if x != nil {
		return x.LogId
	}
	return 0
}

func (x *Event) GetTick() uint32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *Event) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Event) GetEventType() uint32 {
	if x != nil {
		return x.EventType
	}
	return 0
}

func (x *Event) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *Event) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Event) GetBody() *structpb.Struct {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Event) GetIndexInTick() uint32 {
	if x != nil {
		return x.IndexInTick
	}
	return 0
}

func (x *Event) GetLogDigest() string {
	if x != nil {
		return x.LogDigest
	}
	return ""
}

// TickInterval represents a range of ticks
type TickInterval struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstTick     uint32                 `protobuf:"varint,1,opt,name=first_tick,json=firstTick,proto3" json:"first_tick,omitempty"`
	LastTick      uint32                 `protobuf:"varint,2,opt,name=last_tick,json=lastTick,proto3" json:"last_tick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TickInterval) Reset() {
	*x = TickInterval{}
	mi := &file_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickInterval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickInterval) ProtoMessage() {}

func (x *TickInterval) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickInterval.ProtoReflect.Descriptor instead.
func (*TickInterval) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *TickInterval) GetFirstTick() uint32 {
	if x != nil {
		return x.FirstTick
	}
	return 0
}

func (x *TickInterval) GetLastTick() uint32 {
	if x != nil {
		return x.LastTick
	}
	return 0
}

// EpochInfo contains information about a single epoch
type EpochInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint32                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Intervals     []*TickInterval        `protobuf:"bytes,2,rep,name=intervals,proto3" json:"intervals,omitempty"`
	TotalEvents   uint64                 `protobuf:"varint,3,opt,name=total_events,json=totalEvents,proto3" json:"total_events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EpochInfo) Reset() {
	*x = EpochInfo{}
	mi := &file_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpochInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpochInfo) ProtoMessage() {}

func (x *EpochInfo) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpochInfo.ProtoReflect.Descriptor instead.
func (*EpochInfo) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *EpochInfo) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *EpochInfo) GetIntervals() []*TickInterval {
	if x != nil {
		return x.Intervals
	}
	return nil
}

func (x *EpochInfo) GetTotalEvents() uint64 {
	if x != nil {
		return x.TotalEvents
	}
	return 0
}

// GetStatusResponse contains service status information
type GetStatusResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Epochs             []*EpochInfo           `protobuf:"bytes,1,rep,name=epochs,proto3" json:"epochs,omitempty"`
	CurrentEpoch       uint32                 `protobuf:"varint,2,opt,name=current_epoch,json=currentEpoch,proto3" json:"current_epoch,omitempty"`
	LastProcessedTick  uint32                 `protobuf:"varint,3,opt,name=last_processed_tick,json=lastProcessedTick,proto3" json:"last_processed_tick,omitempty"`
	LastProcessedLogId int64                  `protobuf:"varint,4,opt,name=last_processed_log_id,json=lastProcessedLogId,proto3" json:"last_processed_log_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatusResponse) GetEpochs() []*EpochInfo {
	if x != nil {
		return x.Epochs
	}
	return nil
}

func (x *GetStatusResponse) GetCurrentEpoch() uint32 {
	if x != nil {
		return x.CurrentEpoch
	}
	return 0
}

func (x *GetStatusResponse) GetLastProcessedTick() uint32 {
	if x != nil {
		return x.LastProcessedTick
	}
	return 0
}

func (x *GetStatusResponse) GetLastProcessedLogId() int64 {
	if x != nil {
		return x.LastProcessedLogId
	}
	return 0
}

// GetEventsForTickRequest is the request for getting events for a tick
type GetEventsForTickRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          uint32                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsForTickRequest) Reset() {
	*x = GetEventsForTickRequest{}
	mi := &file_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsForTickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsForTickRequest) ProtoMessage() {}

func (x *GetEventsForTickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsForTickRequest.ProtoReflect.Descriptor instead.
func (*GetEventsForTickRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *GetEventsForTickRequest) GetTick() uint32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

// GetEventsForTickResponse contains events for a specific tick
type GetEventsForTickResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          uint32                 `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Epoch         uint32                 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Events        []*Event               `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsForTickResponse) Reset() {
	*x = GetEventsForTickResponse{}
	mi := &file_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsForTickResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsForTickResponse) ProtoMessage() {}

func (x *GetEventsForTickResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsForTickResponse.ProtoReflect.Descriptor instead.
func (*GetEventsForTickResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *GetEventsForTickResponse) GetTick() uint32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *GetEventsForTickResponse) GetEpoch() uint32 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *GetEventsForTickResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\x12\x10events_bridge.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x8e\x02\n" +
	"\x05Event\x12\x15\n" +
	"\x06log_id\x18\x01 \x01(\x04R\x05logId\x12\x12\n" +
	"\x04tick\x18\x02 \x01(\rR\x04tick\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\rR\x05epoch\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\rR\teventType\x12\x17\n" +
	"\atx_hash\x18\x05 \x01(\tR\x06txHash\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x04R\ttimestamp\x12+\n" +
	"\x04body\x18\a \x01(\v2\x17.google.protobuf.StructR\x04body\x12\"\n" +
	"\rindex_in_tick\x18\b \x01(\rR\vindexInTick\x12\x1d\n" +
	"\n" +
	"log_digest\x18\t \x01(\tR\tlogDigest\"J\n" +
	"\fTickInterval\x12\x1d\n" +
	"\n" +
	"first_tick\x18\x01 \x01(\rR\tfirstTick\x12\x1b\n" +
	"\tlast_tick\x18\x02 \x01(\rR\blastTick\"\x82\x01\n" +
	"\tEpochInfo\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\rR\x05epoch\x12<\n" +
	"\tintervals\x18\x02 \x03(\v2\x1e.events_bridge.v1.TickIntervalR\tintervals\x12!\n" +
	"\ftotal_events\x18\x03 \x01(\x04R\vtotalEvents\"\xd0\x01\n" +
	"\x11GetStatusResponse\x123\n" +
	"\x06epochs\x18\x01 \x03(\v2\x1b.events_bridge.v1.EpochInfoR\x06epochs\x12#\n" +
	"\rcurrent_epoch\x18\x02 \x01(\rR\fcurrentEpoch\x12.\n" +
	"\x13last_processed_tick\x18\x03 \x01(\rR\x11lastProcessedTick\x121\n" +
	"\x15last_processed_log_id\x18\x04 \x01(\x03R\x12lastProcessedLogId\"-\n" +
	"\x17GetEventsForTickRequest\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\rR\x04tick\"u\n" +
	"\x18GetEventsForTickResponse\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\rR\x04tick\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\rR\x05epoch\x12/\n" +
	"\x06events\x18\x03 \x03(\v2\x17.events_bridge.v1.EventR\x06eventsBFZDgithub.com/qubic/bob-events-bridge/api/events-bridge/v1;eventsbridgeb\x06proto3"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_messages_proto_goTypes = []any{
	(*Event)(nil),                    // 0: events_bridge.v1.Event
	(*TickInterval)(nil),             // 1: events_bridge.v1.TickInterval
	(*EpochInfo)(nil),                // 2: events_bridge.v1.EpochInfo
	(*GetStatusResponse)(nil),        // 3: events_bridge.v1.GetStatusResponse
	(*GetEventsForTickRequest)(nil),  // 4: events_bridge.v1.GetEventsForTickRequest
	(*GetEventsForTickResponse)(nil), // 5: events_bridge.v1.GetEventsForTickResponse
	(*structpb.Struct)(nil),          // 6: google.protobuf.Struct
}
var file_messages_proto_depIdxs = []int32{
	6, // 0: events_bridge.v1.Event.body:type_name -> google.protobuf.Struct
	1, // 1: events_bridge.v1.EpochInfo.intervals:type_name -> events_bridge.v1.TickInterval
	2, // 2: events_bridge.v1.GetStatusResponse.epochs:type_name -> events_bridge.v1.EpochInfo
	0, // 3: events_bridge.v1.GetEventsForTickResponse.events:type_name -> events_bridge.v1.Event
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
