// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: service.proto

package eventsbridge

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventsBridgeService_GetStatus_FullMethodName        = "/events_bridge.v1.EventsBridgeService/GetStatus"
	EventsBridgeService_GetEventsForTick_FullMethodName = "/events_bridge.v1.EventsBridgeService/GetEventsForTick"
)

// EventsBridgeServiceClient is the client API for EventsBridgeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EventsBridgeService provides access to stored bob events
type EventsBridgeServiceClient interface {
	// GetStatus returns the current service status including available epochs and intervals
	GetStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetStatusResponse, error)
	// GetEventsForTick returns all events for a specific tick
	GetEventsForTick(ctx context.Context, in *GetEventsForTickRequest, opts ...grpc.CallOption) (*GetEventsForTickResponse, error)
}

type eventsBridgeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventsBridgeServiceClient(cc grpc.ClientConnInterface) EventsBridgeServiceClient {
	return &eventsBridgeServiceClient{cc}
}

func (c *eventsBridgeServiceClient) GetStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, EventsBridgeService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsBridgeServiceClient) GetEventsForTick(ctx context.Context, in *GetEventsForTickRequest, opts ...grpc.CallOption) (*GetEventsForTickResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventsForTickResponse)
	err := c.cc.Invoke(ctx, EventsBridgeService_GetEventsForTick_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventsBridgeServiceServer is the server API for EventsBridgeService service.
// All implementations must embed UnimplementedEventsBridgeServiceServer
// for forward compatibility.
//
// EventsBridgeService provides access to stored bob events
type EventsBridgeServiceServer interface {
	// GetStatus returns the current service status including available epochs and intervals
	GetStatus(context.Context, *emptypb.Empty) (*GetStatusResponse, error)
	// GetEventsForTick returns all events for a specific tick
	GetEventsForTick(context.Context, *GetEventsForTickRequest) (*GetEventsForTickResponse, error)
	mustEmbedUnimplementedEventsBridgeServiceServer()
}

// UnimplementedEventsBridgeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventsBridgeServiceServer struct{}

func (UnimplementedEventsBridgeServiceServer) GetStatus(context.Context, *emptypb.Empty) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedEventsBridgeServiceServer) GetEventsForTick(context.Context, *GetEventsForTickRequest) (*GetEventsForTickResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEventsForTick not implemented")
}
func (UnimplementedEventsBridgeServiceServer) mustEmbedUnimplementedEventsBridgeServiceServer() {}
func (UnimplementedEventsBridgeServiceServer) testEmbeddedByValue()                             {}

// UnsafeEventsBridgeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventsBridgeServiceServer will
// result in compilation errors.
type UnsafeEventsBridgeServiceServer interface {
	mustEmbedUnimplementedEventsBridgeServiceServer()
}

func RegisterEventsBridgeServiceServer(s grpc.ServiceRegistrar, srv EventsBridgeServiceServer) {
	// If the following call panics, it indicates UnimplementedEventsBridgeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventsBridgeService_ServiceDesc, srv)
}

func _EventsBridgeService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsBridgeServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsBridgeService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsBridgeServiceServer).GetStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsBridgeService_GetEventsForTick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsForTickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsBridgeServiceServer).GetEventsForTick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsBridgeService_GetEventsForTick_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsBridgeServiceServer).GetEventsForTick(ctx, req.(*GetEventsForTickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventsBridgeService_ServiceDesc is the grpc.ServiceDesc for EventsBridgeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventsBridgeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "events_bridge.v1.EventsBridgeService",
	HandlerType: (*EventsBridgeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _EventsBridgeService_GetStatus_Handler,
		},
		{
			MethodName: "GetEventsForTick",
			Handler:    _EventsBridgeService_GetEventsForTick_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
