// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: service.proto

package eventsbridge

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x10events_bridge.v1\x1a\x0emessages.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto2\x80\x02\n" +
	"\x13EventsBridgeService\x12\\\n" +
	"\tGetStatus\x12\x16.google.protobuf.Empty\x1a#.events_bridge.v1.GetStatusResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/status\x12\x8a\x01\n" +
	"\x10GetEventsForTick\x12).events_bridge.v1.GetEventsForTickRequest\x1a*.events_bridge.v1.GetEventsForTickResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/getEventsForTickBFZDgithub.com/qubic/bob-events-bridge/api/events-bridge/v1;eventsbridgeb\x06proto3"

var file_service_proto_goTypes = []any{
	(*emptypb.Empty)(nil),            // 0: google.protobuf.Empty
	(*GetEventsForTickRequest)(nil),  // 1: events_bridge.v1.GetEventsForTickRequest
	(*GetStatusResponse)(nil),        // 2: events_bridge.v1.GetStatusResponse
	(*GetEventsForTickResponse)(nil), // 3: events_bridge.v1.GetEventsForTickResponse
}
var file_service_proto_depIdxs = []int32{
	0, // 0: events_bridge.v1.EventsBridgeService.GetStatus:input_type -> google.protobuf.Empty
	1, // 1: events_bridge.v1.EventsBridgeService.GetEventsForTick:input_type -> events_bridge.v1.GetEventsForTickRequest
	2, // 2: events_bridge.v1.EventsBridgeService.GetStatus:output_type -> events_bridge.v1.GetStatusResponse
	3, // 3: events_bridge.v1.EventsBridgeService.GetEventsForTick:output_type -> events_bridge.v1.GetEventsForTickResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
